### ISSUE TITLE
Package in CPAN is old

### ISSUE THREAD

**Issue by tokuhirom** [dlc/toml#2]
Hi,
I guess the module uploaded on CPAN is broken, but fixed at repo.
Can you release latest git version to CPAN?

**Comment by dlc** [comment]
I just merged your changes, and I need to update the docs and bump the version number. I'll release 0.91 to CPAN today. Thanks for your help!

**Comment by dlc** [comment]
TOML 0.91 is on its way to CPAN now, with updated docs and additional tests.

**Comment by tokuhirom** [comment]
Thanks!
